image: node:6

stages:
  - build

production build:
  only:
    - master
  stage: build
  script:
    - apt-get update -y && apt-get install apt-transport-https -y
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - apt-get update -y && apt-get install git yarn -y
    - yarn install
    - yarn global add jest
    - export PATH="./node_modules/.bin:$PATH"
    - rm -rf dist
    - rm -rf dist_landing
    - yarn build
    - yarn build:landing
    - wget -O- -q http://s3tools.org/repo/deb-all/stable/s3tools.key | apt-key add -
    - wget -O/etc/apt/sources.list.d/s3tools.list http://s3tools.org/repo/deb-all/stable/s3tools.list
    - apt-get update -y && apt-get install s3cmd -y
    - s3cmd sync ./dist_landing/  s3://menshend.io/
    - mkdir -p $HOME/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git config --global user.name "nebot"
    - git config --global user.email devbot@nebtex.com
    - echo -e "$nebot_key" > $HOME/.ssh/id_rsa
    - echo -e "$nebot_gpg" > $HOME/private.key
    - gpg --import $HOME/private.key
    - git config --global user.signingkey $nebot_secret_key_gpg
    - chmod 400 $HOME/.ssh/id_rsa
    - git clone git@github.com:nebtex/menshend.git
    - rm -rf  menshend/ui
    - mkdir -p menshend/ui
    - rm -rf ./dist/landing
    - cp -r ./dist/* menshend/ui/
    - cd menshend 
    - git add .
    - git commit -S -m "update ui to the latest version"
    - git push origin master